name: prod_build

on:
  push:
    branches:
      - prod-deploy

jobs:
  build:
    runs-on: [self-hosted, Prod]

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Verificar Node
        run: |
          node -v
          npm -v

      - name: Limpiar cache npm
        run: npm cache clean --force

      - name: Instalar dependencias
        run: npm ci --verbose

      - name: Ejecutar build
        run: npm run build

      - name: Verificar carpeta dist
        run: ls -la dist

      - name: Copiar build a Nginx
        run: |
          rm -rf /var/www/html/sied/*
          cp -r dist/* /var/www/html/sied/
